-- Phase 4 perf tune-up: wrap RLS auth-function calls in a scalar subquery so
-- Postgres caches the result ONCE per query (InitPlan) instead of calling
-- current_tenant_id()/jwt_tenant_id()/auth.uid()/auth.jwt() again for every row.
-- Supabase's own RLS performance guidance: use `(select fn())` instead of `fn()`.
-- (docs: "RLS Performance and Best Practices" — wrapping auth functions in a
-- subquery lets the optimizer evaluate them once via initPlan.)
--
-- SAFETY: this is a pure caching optimization, not a logic change. Every
-- statement below was generated by mechanically wrapping bare function calls
-- and PROVEN correct by round-trip: stripping "(select FN())" back to "FN()"
-- reproduces the original policy text byte-for-byte (proof script:
-- scripts one-off, not checked in — see TENANT-ISOLATION-AND-CLONE-PLAN.md
-- Phase 4 for the method). Uses ALTER POLICY (not drop+create) so each
-- policy's name/roles/command are untouched and there is never a moment
-- where the policy doesn't exist.
--
-- Applied to prod 2026-06-30 and verified: 0 bare (unwrapped) calls remain;
-- isolation regression matrix (12 tables, 2 tenants) shows 0 foreign rows;
-- a forged cross-tenant INSERT is still rejected by RLS (42501); public site
-- + admin-canary (auth.admin.listUsers) health checks pass. Idempotent
-- (ALTER POLICY re-applying the same USING/WITH CHECK is a no-op).

alter policy "Tenant users can delete api_keys" on public."api_keys"
  using (((( SELECT auth.uid() AS uid) IS NOT NULL) AND ((tenant_id IS NULL) OR ((tenant_id)::text = (((select auth.jwt()) -> 'app_metadata'::text) ->> 'tenant_id'::text)))));
alter policy "Tenant users can create api_keys" on public."api_keys"
  with check (((( SELECT auth.uid() AS uid) IS NOT NULL) AND ((tenant_id IS NULL) OR ((tenant_id)::text = (((select auth.jwt()) -> 'app_metadata'::text) ->> 'tenant_id'::text)))));
alter policy "Tenant users can view api_keys" on public."api_keys"
  using (((( SELECT auth.uid() AS uid) IS NOT NULL) AND ((tenant_id IS NULL) OR ((tenant_id)::text = (((select auth.jwt()) -> 'app_metadata'::text) ->> 'tenant_id'::text)))));
alter policy "Tenant users can update api_keys" on public."api_keys"
  using (((( SELECT auth.uid() AS uid) IS NOT NULL) AND ((tenant_id IS NULL) OR ((tenant_id)::text = (((select auth.jwt()) -> 'app_metadata'::text) ->> 'tenant_id'::text)))))
  with check (((( SELECT auth.uid() AS uid) IS NOT NULL) AND ((tenant_id IS NULL) OR ((tenant_id)::text = (((select auth.jwt()) -> 'app_metadata'::text) ->> 'tenant_id'::text)))));
alter policy "app_settings_tenant_all" on public."app_settings"
  using ((tenant_id = (select current_tenant_id())))
  with check ((tenant_id = (select current_tenant_id())));
alter policy "asset_folders_tenant_delete" on public."asset_folders"
  using ((tenant_id = (select current_tenant_id())));
alter policy "tenant_delete" on public."asset_folders"
  using ((tenant_id = (select jwt_tenant_id())));
alter policy "asset_folders_tenant_insert" on public."asset_folders"
  with check ((tenant_id = (select current_tenant_id())));
alter policy "tenant_insert" on public."asset_folders"
  with check ((tenant_id = (select jwt_tenant_id())));
alter policy "asset_folders_tenant_select" on public."asset_folders"
  using ((tenant_id = (select current_tenant_id())));
alter policy "tenant_select" on public."asset_folders"
  using (((((select auth.uid()) IS NULL) AND (is_published = true) AND (deleted_at IS NULL)) OR (((select auth.uid()) IS NOT NULL) AND (tenant_id = (select jwt_tenant_id())))));
alter policy "asset_folders_tenant_update" on public."asset_folders"
  using ((tenant_id = (select current_tenant_id())))
  with check ((tenant_id = (select current_tenant_id())));
alter policy "tenant_update" on public."asset_folders"
  using ((tenant_id = (select jwt_tenant_id())));
alter policy "assets_tenant_delete" on public."assets"
  using ((tenant_id = (select current_tenant_id())));
alter policy "tenant_delete" on public."assets"
  using ((tenant_id = (select jwt_tenant_id())));
alter policy "assets_tenant_insert" on public."assets"
  with check ((tenant_id = (select current_tenant_id())));
alter policy "tenant_insert" on public."assets"
  with check ((tenant_id = (select jwt_tenant_id())));
alter policy "assets_tenant_select" on public."assets"
  using ((tenant_id = (select current_tenant_id())));
alter policy "tenant_select" on public."assets"
  using (((((select auth.uid()) IS NULL) AND (is_published = true) AND (deleted_at IS NULL)) OR (((select auth.uid()) IS NOT NULL) AND (tenant_id = (select jwt_tenant_id())))));
alter policy "assets_tenant_update" on public."assets"
  using ((tenant_id = (select current_tenant_id())))
  with check ((tenant_id = (select current_tenant_id())));
alter policy "tenant_update" on public."assets"
  using ((tenant_id = (select jwt_tenant_id())));
alter policy "collection_fields_tenant_delete" on public."collection_fields"
  using ((tenant_id = (select current_tenant_id())));
alter policy "tenant_delete" on public."collection_fields"
  using ((tenant_id = (select jwt_tenant_id())));
alter policy "collection_fields_tenant_insert" on public."collection_fields"
  with check ((tenant_id = (select current_tenant_id())));
alter policy "tenant_insert" on public."collection_fields"
  with check ((tenant_id = (select jwt_tenant_id())));
alter policy "collection_fields_tenant_select" on public."collection_fields"
  using ((tenant_id = (select current_tenant_id())));
alter policy "tenant_select" on public."collection_fields"
  using (((((select auth.uid()) IS NULL) AND (is_published = true) AND (deleted_at IS NULL)) OR (((select auth.uid()) IS NOT NULL) AND (tenant_id = (select jwt_tenant_id())))));
alter policy "collection_fields_tenant_update" on public."collection_fields"
  using ((tenant_id = (select current_tenant_id())))
  with check ((tenant_id = (select current_tenant_id())));
alter policy "tenant_update" on public."collection_fields"
  using ((tenant_id = (select jwt_tenant_id())));
alter policy "collection_imports_tenant_all" on public."collection_imports"
  using ((tenant_id = (select current_tenant_id())))
  with check ((tenant_id = (select current_tenant_id())));
alter policy "collection_item_values_tenant_delete" on public."collection_item_values"
  using ((tenant_id = (select current_tenant_id())));
alter policy "tenant_delete" on public."collection_item_values"
  using ((tenant_id = (select jwt_tenant_id())));
alter policy "collection_item_values_tenant_insert" on public."collection_item_values"
  with check ((tenant_id = (select current_tenant_id())));
alter policy "tenant_insert" on public."collection_item_values"
  with check ((tenant_id = (select jwt_tenant_id())));
alter policy "collection_item_values_tenant_select" on public."collection_item_values"
  using ((tenant_id = (select current_tenant_id())));
alter policy "tenant_select" on public."collection_item_values"
  using (((((select auth.uid()) IS NULL) AND (is_published = true) AND (deleted_at IS NULL)) OR (((select auth.uid()) IS NOT NULL) AND (tenant_id = (select jwt_tenant_id())))));
alter policy "collection_item_values_tenant_update" on public."collection_item_values"
  using ((tenant_id = (select current_tenant_id())))
  with check ((tenant_id = (select current_tenant_id())));
alter policy "tenant_update" on public."collection_item_values"
  using ((tenant_id = (select jwt_tenant_id())));
alter policy "collection_items_tenant_delete" on public."collection_items"
  using ((tenant_id = (select current_tenant_id())));
alter policy "tenant_delete" on public."collection_items"
  using ((tenant_id = (select jwt_tenant_id())));
alter policy "collection_items_tenant_insert" on public."collection_items"
  with check ((tenant_id = (select current_tenant_id())));
alter policy "tenant_insert" on public."collection_items"
  with check ((tenant_id = (select jwt_tenant_id())));
alter policy "collection_items_tenant_select" on public."collection_items"
  using ((tenant_id = (select current_tenant_id())));
alter policy "tenant_select" on public."collection_items"
  using (((((select auth.uid()) IS NULL) AND (is_published = true) AND (deleted_at IS NULL)) OR (((select auth.uid()) IS NOT NULL) AND (tenant_id = (select jwt_tenant_id())))));
alter policy "collection_items_tenant_update" on public."collection_items"
  using ((tenant_id = (select current_tenant_id())))
  with check ((tenant_id = (select current_tenant_id())));
alter policy "tenant_update" on public."collection_items"
  using ((tenant_id = (select jwt_tenant_id())));
alter policy "collections_tenant_delete" on public."collections"
  using ((tenant_id = (select current_tenant_id())));
alter policy "tenant_delete" on public."collections"
  using ((tenant_id = (select jwt_tenant_id())));
alter policy "collections_tenant_insert" on public."collections"
  with check ((tenant_id = (select current_tenant_id())));
alter policy "tenant_insert" on public."collections"
  with check ((tenant_id = (select jwt_tenant_id())));
alter policy "collections_tenant_select" on public."collections"
  using ((tenant_id = (select current_tenant_id())));
alter policy "tenant_select" on public."collections"
  using (((((select auth.uid()) IS NULL) AND (is_published = true) AND (deleted_at IS NULL)) OR (((select auth.uid()) IS NOT NULL) AND (tenant_id = (select jwt_tenant_id())))));
alter policy "collections_tenant_update" on public."collections"
  using ((tenant_id = (select current_tenant_id())))
  with check ((tenant_id = (select current_tenant_id())));
alter policy "tenant_update" on public."collections"
  using ((tenant_id = (select jwt_tenant_id())));
alter policy "color_variables_tenant_delete" on public."color_variables"
  using ((tenant_id = (select current_tenant_id())));
alter policy "tenant_delete" on public."color_variables"
  using ((tenant_id = (select jwt_tenant_id())));
alter policy "color_variables_tenant_insert" on public."color_variables"
  with check ((tenant_id = (select current_tenant_id())));
alter policy "tenant_insert" on public."color_variables"
  with check ((tenant_id = (select jwt_tenant_id())));
alter policy "color_variables_tenant_select" on public."color_variables"
  using ((tenant_id = (select current_tenant_id())));
alter policy "tenant_select" on public."color_variables"
  using ((((select auth.uid()) IS NULL) OR (tenant_id = (select jwt_tenant_id()))));
alter policy "color_variables_tenant_update" on public."color_variables"
  using ((tenant_id = (select current_tenant_id())))
  with check ((tenant_id = (select current_tenant_id())));
alter policy "tenant_update" on public."color_variables"
  using ((tenant_id = (select jwt_tenant_id())));
alter policy "components_tenant_delete" on public."components"
  using ((tenant_id = (select current_tenant_id())));
alter policy "tenant_delete" on public."components"
  using ((tenant_id = (select jwt_tenant_id())));
alter policy "components_tenant_insert" on public."components"
  with check ((tenant_id = (select current_tenant_id())));
alter policy "tenant_insert" on public."components"
  with check ((tenant_id = (select jwt_tenant_id())));
alter policy "components_tenant_select" on public."components"
  using ((tenant_id = (select current_tenant_id())));
alter policy "tenant_select" on public."components"
  using (((((select auth.uid()) IS NULL) AND (is_published = true) AND (deleted_at IS NULL)) OR (((select auth.uid()) IS NOT NULL) AND (tenant_id = (select jwt_tenant_id())))));
alter policy "components_tenant_update" on public."components"
  using ((tenant_id = (select current_tenant_id())))
  with check ((tenant_id = (select current_tenant_id())));
alter policy "tenant_update" on public."components"
  using ((tenant_id = (select jwt_tenant_id())));
alter policy "fonts_tenant_delete" on public."fonts"
  using ((tenant_id = (select current_tenant_id())));
alter policy "tenant_delete" on public."fonts"
  using ((tenant_id = (select jwt_tenant_id())));
alter policy "fonts_tenant_insert" on public."fonts"
  with check ((tenant_id = (select current_tenant_id())));
alter policy "tenant_insert" on public."fonts"
  with check ((tenant_id = (select jwt_tenant_id())));
alter policy "fonts_tenant_select" on public."fonts"
  using ((tenant_id = (select current_tenant_id())));
alter policy "tenant_select" on public."fonts"
  using (((((select auth.uid()) IS NULL) AND (is_published = true) AND (deleted_at IS NULL)) OR (((select auth.uid()) IS NOT NULL) AND (tenant_id = (select jwt_tenant_id())))));
alter policy "fonts_tenant_update" on public."fonts"
  using ((tenant_id = (select current_tenant_id())))
  with check ((tenant_id = (select current_tenant_id())));
alter policy "tenant_update" on public."fonts"
  using ((tenant_id = (select jwt_tenant_id())));
alter policy "Tenant users can delete form submissions" on public."form_submissions"
  using (((( SELECT auth.uid() AS uid) IS NOT NULL) AND ((tenant_id IS NULL) OR ((tenant_id)::text = (((select auth.jwt()) -> 'app_metadata'::text) ->> 'tenant_id'::text)))));
alter policy "Tenant users can view form submissions" on public."form_submissions"
  using (((( SELECT auth.uid() AS uid) IS NOT NULL) AND ((tenant_id IS NULL) OR ((tenant_id)::text = (((select auth.jwt()) -> 'app_metadata'::text) ->> 'tenant_id'::text)))));
alter policy "Tenant users can update form submissions" on public."form_submissions"
  using (((( SELECT auth.uid() AS uid) IS NOT NULL) AND ((tenant_id IS NULL) OR ((tenant_id)::text = (((select auth.jwt()) -> 'app_metadata'::text) ->> 'tenant_id'::text)))))
  with check (((( SELECT auth.uid() AS uid) IS NOT NULL) AND ((tenant_id IS NULL) OR ((tenant_id)::text = (((select auth.jwt()) -> 'app_metadata'::text) ->> 'tenant_id'::text)))));
alter policy "global_variables_tenant_all" on public."global_variables"
  using ((tenant_id = (select current_tenant_id())))
  with check ((tenant_id = (select current_tenant_id())));
alter policy "layer_styles_tenant_delete" on public."layer_styles"
  using ((tenant_id = (select current_tenant_id())));
alter policy "tenant_delete" on public."layer_styles"
  using ((tenant_id = (select jwt_tenant_id())));
alter policy "layer_styles_tenant_insert" on public."layer_styles"
  with check ((tenant_id = (select current_tenant_id())));
alter policy "tenant_insert" on public."layer_styles"
  with check ((tenant_id = (select jwt_tenant_id())));
alter policy "layer_styles_tenant_select" on public."layer_styles"
  using ((tenant_id = (select current_tenant_id())));
alter policy "tenant_select" on public."layer_styles"
  using (((((select auth.uid()) IS NULL) AND (is_published = true) AND (deleted_at IS NULL)) OR (((select auth.uid()) IS NOT NULL) AND (tenant_id = (select jwt_tenant_id())))));
alter policy "layer_styles_tenant_update" on public."layer_styles"
  using ((tenant_id = (select current_tenant_id())))
  with check ((tenant_id = (select current_tenant_id())));
alter policy "tenant_update" on public."layer_styles"
  using ((tenant_id = (select jwt_tenant_id())));
alter policy "locales_tenant_delete" on public."locales"
  using ((tenant_id = (select current_tenant_id())));
alter policy "tenant_delete" on public."locales"
  using ((tenant_id = (select jwt_tenant_id())));
alter policy "locales_tenant_insert" on public."locales"
  with check ((tenant_id = (select current_tenant_id())));
alter policy "tenant_insert" on public."locales"
  with check ((tenant_id = (select jwt_tenant_id())));
alter policy "locales_tenant_select" on public."locales"
  using ((tenant_id = (select current_tenant_id())));
alter policy "tenant_select" on public."locales"
  using (((((select auth.uid()) IS NULL) AND (is_published = true) AND (deleted_at IS NULL)) OR (((select auth.uid()) IS NOT NULL) AND (tenant_id = (select jwt_tenant_id())))));
alter policy "locales_tenant_update" on public."locales"
  using ((tenant_id = (select current_tenant_id())))
  with check ((tenant_id = (select current_tenant_id())));
alter policy "tenant_update" on public."locales"
  using ((tenant_id = (select jwt_tenant_id())));
alter policy "mcp_tokens_tenant_all" on public."mcp_tokens"
  using ((tenant_id = (select current_tenant_id())))
  with check ((tenant_id = (select current_tenant_id())));
alter policy "tenant_delete" on public."page_folders"
  using ((tenant_id = (select jwt_tenant_id())));
alter policy "tenant_insert" on public."page_folders"
  with check ((tenant_id = (select jwt_tenant_id())));
alter policy "tenant_select" on public."page_folders"
  using (((((select auth.uid()) IS NULL) AND (is_published = true) AND (deleted_at IS NULL)) OR (((select auth.uid()) IS NOT NULL) AND (tenant_id = (select jwt_tenant_id())))));
alter policy "tenant_update" on public."page_folders"
  using ((tenant_id = (select jwt_tenant_id())));
alter policy "page_layers_tenant_delete" on public."page_layers"
  using ((tenant_id = (select current_tenant_id())));
alter policy "tenant_delete" on public."page_layers"
  using ((tenant_id = (select jwt_tenant_id())));
alter policy "page_layers_tenant_insert" on public."page_layers"
  with check ((tenant_id = (select current_tenant_id())));
alter policy "tenant_insert" on public."page_layers"
  with check ((tenant_id = (select jwt_tenant_id())));
alter policy "page_layers_tenant_select" on public."page_layers"
  using ((tenant_id = (select current_tenant_id())));
alter policy "tenant_select" on public."page_layers"
  using (((((select auth.uid()) IS NULL) AND (is_published = true) AND (deleted_at IS NULL) AND (EXISTS ( SELECT 1
   FROM pages
  WHERE ((pages.id = page_layers.page_id) AND (pages.is_published = true) AND (pages.deleted_at IS NULL))))) OR (((select auth.uid()) IS NOT NULL) AND (tenant_id = (select jwt_tenant_id())))));
alter policy "page_layers_tenant_update" on public."page_layers"
  using ((tenant_id = (select current_tenant_id())))
  with check ((tenant_id = (select current_tenant_id())));
alter policy "tenant_update" on public."page_layers"
  using ((tenant_id = (select jwt_tenant_id())));
alter policy "pages_tenant_delete" on public."pages"
  using ((tenant_id = (select current_tenant_id())));
alter policy "tenant_delete" on public."pages"
  using ((tenant_id = (select jwt_tenant_id())));
alter policy "pages_tenant_insert" on public."pages"
  with check ((tenant_id = (select current_tenant_id())));
alter policy "tenant_insert" on public."pages"
  with check ((tenant_id = (select jwt_tenant_id())));
alter policy "pages_tenant_select" on public."pages"
  using ((tenant_id = (select current_tenant_id())));
alter policy "tenant_select" on public."pages"
  using (((((select auth.uid()) IS NULL) AND (is_published = true) AND (deleted_at IS NULL)) OR (((select auth.uid()) IS NOT NULL) AND (tenant_id = (select jwt_tenant_id())))));
alter policy "pages_tenant_update" on public."pages"
  using ((tenant_id = (select current_tenant_id())))
  with check ((tenant_id = (select current_tenant_id())));
alter policy "tenant_update" on public."pages"
  using ((tenant_id = (select jwt_tenant_id())));
alter policy "settings_tenant_delete" on public."settings"
  using ((tenant_id = (select current_tenant_id())));
alter policy "tenant_delete" on public."settings"
  using ((tenant_id = (select jwt_tenant_id())));
alter policy "settings_tenant_insert" on public."settings"
  with check ((tenant_id = (select current_tenant_id())));
alter policy "tenant_insert" on public."settings"
  with check ((tenant_id = (select jwt_tenant_id())));
alter policy "settings_tenant_select" on public."settings"
  using ((tenant_id = (select current_tenant_id())));
alter policy "tenant_select" on public."settings"
  using ((tenant_id = (select jwt_tenant_id())));
alter policy "settings_tenant_update" on public."settings"
  using ((tenant_id = (select current_tenant_id())))
  with check ((tenant_id = (select current_tenant_id())));
alter policy "tenant_update" on public."settings"
  using ((tenant_id = (select jwt_tenant_id())));
alter policy "translations_tenant_all" on public."translations"
  using ((tenant_id = (select current_tenant_id())))
  with check ((tenant_id = (select current_tenant_id())));
alter policy "versions_tenant_all" on public."versions"
  using ((tenant_id = (select current_tenant_id())))
  with check ((tenant_id = (select current_tenant_id())));
alter policy "webhook_deliveries_tenant_all" on public."webhook_deliveries"
  using ((tenant_id = (select current_tenant_id())))
  with check ((tenant_id = (select current_tenant_id())));
alter policy "webhooks_tenant_all" on public."webhooks"
  using ((tenant_id = (select current_tenant_id())))
  with check ((tenant_id = (select current_tenant_id())));